inference_start_time: '2024-04-27T16:21:42.164023'
model_class: TimeDistributedEfficientNet
predict_config:
  batch_size: 2
  checkpoint: /home/vilexender/.cache/zamba/european_0a80dc77bf.ckpt
  data_dir: example_vids
  dry_run: false
  gpus: 1
  model_cache_dir: /home/vilexender/.cache/zamba
  model_name: european
  num_workers: 3
  output_class_names: false
  overwrite: false
  proba_threshold: null
  save: true
  save_dir: /home/vilexender
  skip_load_validation: false
  weight_download_region: us
species:
- bird
- blank
- domestic_cat
- european_badger
- european_beaver
- european_hare
- european_roe_deer
- north_american_raccoon
- red_fox
- weasel
- wild_boar
video_loader_config:
  cache_dir: null
  cleanup_cache: false
  crop_bottom_pixels: 50
  early_bias: false
  ensure_total_frames: true
  evenly_sample_total_frames: false
  fps: 4.0
  frame_indices: null
  frame_selection_height: null
  frame_selection_width: null
  i_frames: false
  megadetector_lite_config:
    confidence: 0.25
    device: cuda
    fill_mode: score_sorted
    frame_batch_size: 24
    image_height: 416
    image_width: 416
    n_frames: 16
    nms_threshold: 0.45
    seed: 55
    sort_by_time: true
  model_input_height: 240
  model_input_width: 426
  pix_fmt: rgb24
  scene_threshold: null
  total_frames: 16
